# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings-basic.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Matcha | Version 0.0.0")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1190, 780))
        MainWindow.setMaximumSize(QtCore.QSize(1190, 780))
        MainWindow.setStyleSheet("background: url(C:\\Users\\Garrett Foy\\Documents\\Project Matcha\\Assets\\mockup.png)")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -20, 1200, 800))
        self.background.setMinimumSize(QtCore.QSize(1200, 800))
        self.background.setMaximumSize(QtCore.QSize(1200, 800))
        self.background.setLineWidth(0)
        self.background.setText("")
        self.background.setWindowIcon(QtGui.QIcon("../Assets/mockup.png"))
        self.background.setPixmap(QtGui.QPixmap("../Assets/mockup.png"))
        self.background.setScaledContents(True)
        self.background.setWordWrap(False)
        self.background.setIndent(0)
        self.background.setObjectName("background")
        self.chromebookButton = QtWidgets.QPushButton(self.centralwidget)
        self.chromebookButton.setGeometry(QtCore.QRect(10, 340, 171, 41))
        self.chromebookButton.setText("")
        self.chromebookButton.setFlat(True)
        self.chromebookButton.setObjectName("chromebookButton")
        self.hotspotButton = QtWidgets.QPushButton(self.centralwidget)
        self.hotspotButton.setGeometry(QtCore.QRect(10, 270, 171, 41))
        self.hotspotButton.setText("")
        self.hotspotButton.setFlat(True)
        self.hotspotButton.setObjectName("hotspotButton")
        self.pairButton = QtWidgets.QPushButton(self.centralwidget)
        self.pairButton.setGeometry(QtCore.QRect(0, 190, 191, 51))
        self.pairButton.setText("")
        self.pairButton.setFlat(True)
        self.pairButton.setObjectName("pairButton")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(10, 130, 171, 41))
        self.registerButton.setText("")
        self.registerButton.setFlat(True)
        self.registerButton.setObjectName("registerButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(10, 710, 171, 61))
        self.exitButton.setAutoFillBackground(False)
        self.exitButton.setText("")
        self.exitButton.setFlat(True)
        self.exitButton.setObjectName("exitButton")
        self.exitButton.clicked.connect(MainWindow.close)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Matcha | Version: 0.0.0", "Matcha | Version 0.0.0"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
